[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplcache.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
