# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
   let g:deoplete#enable_at_startup = 1
   let g:deoplete#enable_ignore_case = 1
   let g:deoplete#enable_smart_case = 1
'''

# deoplete on vim requires plugin 1/2
[[plugins]]
repo = 'roxma/nvim-yarp'

# deoplete on vim requires plugin 2/2
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
