[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'mattn/emmet-vim'
